apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-pod
spec:
  limits:
  - max: 
      cpu: "2"
      memory: "2Gi"
    type: Pod 
--
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-1-container
  labels:
    department: engineering
spec:
  replicas: 2
  minReadySeconds: 30
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: tomcat
          image: tomcat:alpine
          ports: 
            - containerPort: 8080
          resources:
            limits:
              memory: "600Mi"
              cpu: "1000m" #Half a core
            requests:
              memory: "512Mi"
              cpu: "500m"
