apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-1-container
  labels:
    department: engineering
spec:
  replicas: 200
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: tomcat
          image: tomcat:alpine
          ports: 
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m" #Half a core
            requests:
              memory: "256Mi"
              cpu: "250m"
