apiVersion: v1
kind: Pod
metadata:
  name: pod-to-backend
spec:
  containers:
    - name: tomcat
      image: tomcat:alpine
      ports:
      - containerPort: 8080
  nodeSelector:
    app: backend
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-to-frontend
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
  nodeSelector:
    app: frontend

