apiVersion: v1
kind: Pod
metadata:
  name: pod-with-1-container-and-env-and-liveness
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      env:
        - name: DATABASE_IP
          value: server1
      ports:
      - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 30
